#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking_Web.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKS")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_DatPhong(tbl_DatPhong instance);
    partial void Updatetbl_DatPhong(tbl_DatPhong instance);
    partial void Deletetbl_DatPhong(tbl_DatPhong instance);
    partial void Inserttbl_VaiTro(tbl_VaiTro instance);
    partial void Updatetbl_VaiTro(tbl_VaiTro instance);
    partial void Deletetbl_VaiTro(tbl_VaiTro instance);
    partial void Inserttbl_GiaoDich(tbl_GiaoDich instance);
    partial void Updatetbl_GiaoDich(tbl_GiaoDich instance);
    partial void Deletetbl_GiaoDich(tbl_GiaoDich instance);
    partial void Inserttbl_LoaiPhong(tbl_LoaiPhong instance);
    partial void Updatetbl_LoaiPhong(tbl_LoaiPhong instance);
    partial void Deletetbl_LoaiPhong(tbl_LoaiPhong instance);
    partial void Inserttbl_Phong(tbl_Phong instance);
    partial void Updatetbl_Phong(tbl_Phong instance);
    partial void Deletetbl_Phong(tbl_Phong instance);
    partial void Inserttbl_PhongImage(tbl_PhongImage instance);
    partial void Updatetbl_PhongImage(tbl_PhongImage instance);
    partial void Deletetbl_PhongImage(tbl_PhongImage instance);
    partial void Inserttbl_TaiKhoan(tbl_TaiKhoan instance);
    partial void Updatetbl_TaiKhoan(tbl_TaiKhoan instance);
    partial void Deletetbl_TaiKhoan(tbl_TaiKhoan instance);
        #endregion
        public DataClasses1DataContext() :
               base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLKSConnectionString1"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_DatPhong> tbl_DatPhongs
		{
			get
			{
				return this.GetTable<tbl_DatPhong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_VaiTro> tbl_VaiTros
		{
			get
			{
				return this.GetTable<tbl_VaiTro>();
			}
		}
		
		public System.Data.Linq.Table<tbl_GiaoDich> tbl_GiaoDiches
		{
			get
			{
				return this.GetTable<tbl_GiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LoaiPhong> tbl_LoaiPhongs
		{
			get
			{
				return this.GetTable<tbl_LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Phong> tbl_Phongs
		{
			get
			{
				return this.GetTable<tbl_Phong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PhongImage> tbl_PhongImages
		{
			get
			{
				return this.GetTable<tbl_PhongImage>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TaiKhoan> tbl_TaiKhoans
		{
			get
			{
				return this.GetTable<tbl_TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<vw_DanhSachDatPhong> vw_DanhSachDatPhongs
		{
			get
			{
				return this.GetTable<vw_DanhSachDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<vw_ThongKeDoanhThu> vw_ThongKeDoanhThus
		{
			get
			{
				return this.GetTable<vw_ThongKeDoanhThu>();
			}
		}
		
		public System.Data.Linq.Table<vw_DanhSachPhong> vw_DanhSachPhongs
		{
			get
			{
				return this.GetTable<vw_DanhSachPhong>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimPhong")]
		public ISingleResult<sp_TimPhongResult> sp_TimPhong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayNhanPhong", DbType="DateTime2")] System.Nullable<System.DateTime> ngayNhanPhong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayTraPhong", DbType="DateTime2")] System.Nullable<System.DateTime> ngayTraPhong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SucChuaToiDa", DbType="Int")] System.Nullable<int> sucChuaToiDa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngayNhanPhong, ngayTraPhong, sucChuaToiDa);
			return ((ISingleResult<sp_TimPhongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BaoCaoDoanhThuTheoThang")]
		public ISingleResult<sp_BaoCaoDoanhThuTheoThangResult> sp_BaoCaoDoanhThuTheoThang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
			return ((ISingleResult<sp_BaoCaoDoanhThuTheoThangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BaoCaoDoanhThuDatPhong")]
		public ISingleResult<sp_BaoCaoDoanhThuDatPhongResult> sp_BaoCaoDoanhThuDatPhong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thang", DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
			return ((ISingleResult<sp_BaoCaoDoanhThuDatPhongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BaoCaoDoanhThuTheoThang")]
		public ISingleResult<sp_BaoCaoDoanhThuTheoThangResult1> sp_BaoCaoDoanhThuTheoThang1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
			return ((ISingleResult<sp_BaoCaoDoanhThuTheoThangResult1>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DatPhong")]
	public partial class tbl_DatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DatPhongID;
		
		private int _TaiKhoanID;
		
		private int _PhongID;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.DateTime _NgayNhanPhong;
		
		private System.DateTime _NgayTraPhong;
		
		private System.Nullable<int> _SoLuongNguoi;
		
		private System.Nullable<decimal> _TongTien;
		
		private string _TrangThai;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _isDelete;
		
		private System.Nullable<System.DateTime> _Cancelled_at;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private EntitySet<tbl_GiaoDich> _tbl_GiaoDiches;
		
		private EntityRef<tbl_Phong> _tbl_Phong;
		
		private EntityRef<tbl_TaiKhoan> _tbl_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDatPhongIDChanging(int value);
    partial void OnDatPhongIDChanged();
    partial void OnTaiKhoanIDChanging(int value);
    partial void OnTaiKhoanIDChanged();
    partial void OnPhongIDChanging(int value);
    partial void OnPhongIDChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnNgayNhanPhongChanging(System.DateTime value);
    partial void OnNgayNhanPhongChanged();
    partial void OnNgayTraPhongChanging(System.DateTime value);
    partial void OnNgayTraPhongChanged();
    partial void OnSoLuongNguoiChanging(System.Nullable<int> value);
    partial void OnSoLuongNguoiChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnisDeleteChanging(System.Nullable<bool> value);
    partial void OnisDeleteChanged();
    partial void OnCancelled_atChanging(System.Nullable<System.DateTime> value);
    partial void OnCancelled_atChanged();
    partial void OnDelete_atChanging(System.Nullable<System.DateTime> value);
    partial void OnDelete_atChanged();
    #endregion
		
		public tbl_DatPhong()
		{
			this._tbl_GiaoDiches = new EntitySet<tbl_GiaoDich>(new Action<tbl_GiaoDich>(this.attach_tbl_GiaoDiches), new Action<tbl_GiaoDich>(this.detach_tbl_GiaoDiches));
			this._tbl_Phong = default(EntityRef<tbl_Phong>);
			this._tbl_TaiKhoan = default(EntityRef<tbl_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatPhongID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DatPhongID
		{
			get
			{
				return this._DatPhongID;
			}
			set
			{
				if ((this._DatPhongID != value))
				{
					this.OnDatPhongIDChanging(value);
					this.SendPropertyChanging();
					this._DatPhongID = value;
					this.SendPropertyChanged("DatPhongID");
					this.OnDatPhongIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanID", DbType="Int NOT NULL")]
		public int TaiKhoanID
		{
			get
			{
				return this._TaiKhoanID;
			}
			set
			{
				if ((this._TaiKhoanID != value))
				{
					if (this._tbl_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaiKhoanIDChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanID = value;
					this.SendPropertyChanged("TaiKhoanID");
					this.OnTaiKhoanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongID", DbType="Int NOT NULL")]
		public int PhongID
		{
			get
			{
				return this._PhongID;
			}
			set
			{
				if ((this._PhongID != value))
				{
					if (this._tbl_Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongIDChanging(value);
					this.SendPropertyChanging();
					this._PhongID = value;
					this.SendPropertyChanged("PhongID");
					this.OnPhongIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime2")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhanPhong", DbType="DateTime2 NOT NULL")]
		public System.DateTime NgayNhanPhong
		{
			get
			{
				return this._NgayNhanPhong;
			}
			set
			{
				if ((this._NgayNhanPhong != value))
				{
					this.OnNgayNhanPhongChanging(value);
					this.SendPropertyChanging();
					this._NgayNhanPhong = value;
					this.SendPropertyChanged("NgayNhanPhong");
					this.OnNgayNhanPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTraPhong", DbType="DateTime2 NOT NULL")]
		public System.DateTime NgayTraPhong
		{
			get
			{
				return this._NgayTraPhong;
			}
			set
			{
				if ((this._NgayTraPhong != value))
				{
					this.OnNgayTraPhongChanging(value);
					this.SendPropertyChanging();
					this._NgayTraPhong = value;
					this.SendPropertyChanged("NgayTraPhong");
					this.OnNgayTraPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNguoi", DbType="Int")]
		public System.Nullable<int> SoLuongNguoi
		{
			get
			{
				return this._SoLuongNguoi;
			}
			set
			{
				if ((this._SoLuongNguoi != value))
				{
					this.OnSoLuongNguoiChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNguoi = value;
					this.SendPropertyChanged("SoLuongNguoi");
					this.OnSoLuongNguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="Bit")]
		public System.Nullable<bool> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this.OnisDeleteChanging(value);
					this.SendPropertyChanging();
					this._isDelete = value;
					this.SendPropertyChanged("isDelete");
					this.OnisDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cancelled_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Cancelled_at
		{
			get
			{
				return this._Cancelled_at;
			}
			set
			{
				if ((this._Cancelled_at != value))
				{
					this.OnCancelled_atChanging(value);
					this.SendPropertyChanging();
					this._Cancelled_at = value;
					this.SendPropertyChanged("Cancelled_at");
					this.OnCancelled_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this.OnDelete_atChanging(value);
					this.SendPropertyChanging();
					this._Delete_at = value;
					this.SendPropertyChanged("Delete_at");
					this.OnDelete_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_DatPhong_tbl_GiaoDich", Storage="_tbl_GiaoDiches", ThisKey="DatPhongID", OtherKey="DatPhongID")]
		public EntitySet<tbl_GiaoDich> tbl_GiaoDiches
		{
			get
			{
				return this._tbl_GiaoDiches;
			}
			set
			{
				this._tbl_GiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_DatPhong", Storage="_tbl_Phong", ThisKey="PhongID", OtherKey="PhongID", IsForeignKey=true)]
		public tbl_Phong tbl_Phong
		{
			get
			{
				return this._tbl_Phong.Entity;
			}
			set
			{
				tbl_Phong previousValue = this._tbl_Phong.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Phong.Entity = null;
						previousValue.tbl_DatPhongs.Remove(this);
					}
					this._tbl_Phong.Entity = value;
					if ((value != null))
					{
						value.tbl_DatPhongs.Add(this);
						this._PhongID = value.PhongID;
					}
					else
					{
						this._PhongID = default(int);
					}
					this.SendPropertyChanged("tbl_Phong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_TaiKhoan_tbl_DatPhong", Storage="_tbl_TaiKhoan", ThisKey="TaiKhoanID", OtherKey="TaiKhoanID", IsForeignKey=true)]
		public tbl_TaiKhoan tbl_TaiKhoan
		{
			get
			{
				return this._tbl_TaiKhoan.Entity;
			}
			set
			{
				tbl_TaiKhoan previousValue = this._tbl_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tbl_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_TaiKhoan.Entity = null;
						previousValue.tbl_DatPhongs.Remove(this);
					}
					this._tbl_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tbl_DatPhongs.Add(this);
						this._TaiKhoanID = value.TaiKhoanID;
					}
					else
					{
						this._TaiKhoanID = default(int);
					}
					this.SendPropertyChanged("tbl_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_GiaoDiches(tbl_GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tbl_DatPhong = this;
		}
		
		private void detach_tbl_GiaoDiches(tbl_GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tbl_DatPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_VaiTro")]
	public partial class tbl_VaiTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _VaiTro;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private System.Nullable<bool> _isDelete;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private EntitySet<tbl_TaiKhoan> _tbl_TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVaiTroChanging(string value);
    partial void OnVaiTroChanged();
    partial void OnCreate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_atChanged();
    partial void OnisDeleteChanging(System.Nullable<bool> value);
    partial void OnisDeleteChanged();
    partial void OnDelete_atChanging(System.Nullable<System.DateTime> value);
    partial void OnDelete_atChanged();
    #endregion
		
		public tbl_VaiTro()
		{
			this._tbl_TaiKhoans = new EntitySet<tbl_TaiKhoan>(new Action<tbl_TaiKhoan>(this.attach_tbl_TaiKhoans), new Action<tbl_TaiKhoan>(this.detach_tbl_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this.OnCreate_atChanging(value);
					this.SendPropertyChanging();
					this._Create_at = value;
					this.SendPropertyChanged("Create_at");
					this.OnCreate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="Bit")]
		public System.Nullable<bool> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this.OnisDeleteChanging(value);
					this.SendPropertyChanging();
					this._isDelete = value;
					this.SendPropertyChanged("isDelete");
					this.OnisDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this.OnDelete_atChanging(value);
					this.SendPropertyChanging();
					this._Delete_at = value;
					this.SendPropertyChanged("Delete_at");
					this.OnDelete_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_VaiTro_tbl_TaiKhoan", Storage="_tbl_TaiKhoans", ThisKey="VaiTro", OtherKey="VaiTro")]
		public EntitySet<tbl_TaiKhoan> tbl_TaiKhoans
		{
			get
			{
				return this._tbl_TaiKhoans;
			}
			set
			{
				this._tbl_TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_TaiKhoans(tbl_TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_VaiTro = this;
		}
		
		private void detach_tbl_TaiKhoans(tbl_TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_VaiTro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_GiaoDich")]
	public partial class tbl_GiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GiaoDichID;
		
		private int _DatPhongID;
		
		private System.Nullable<decimal> _SoTien;
		
		private string _TrangThai;
		
		private string _PhuongThuc;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private System.Nullable<System.DateTime> _Update_at;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private EntityRef<tbl_DatPhong> _tbl_DatPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGiaoDichIDChanging(int value);
    partial void OnGiaoDichIDChanged();
    partial void OnDatPhongIDChanging(int value);
    partial void OnDatPhongIDChanged();
    partial void OnSoTienChanging(System.Nullable<decimal> value);
    partial void OnSoTienChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnPhuongThucChanging(string value);
    partial void OnPhuongThucChanged();
    partial void OnCreate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_atChanged();
    partial void OnUpdate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdate_atChanged();
    partial void OnDelete_atChanging(System.Nullable<System.DateTime> value);
    partial void OnDelete_atChanged();
    #endregion
		
		public tbl_GiaoDich()
		{
			this._tbl_DatPhong = default(EntityRef<tbl_DatPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaoDichID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GiaoDichID
		{
			get
			{
				return this._GiaoDichID;
			}
			set
			{
				if ((this._GiaoDichID != value))
				{
					this.OnGiaoDichIDChanging(value);
					this.SendPropertyChanging();
					this._GiaoDichID = value;
					this.SendPropertyChanged("GiaoDichID");
					this.OnGiaoDichIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatPhongID", DbType="Int NOT NULL")]
		public int DatPhongID
		{
			get
			{
				return this._DatPhongID;
			}
			set
			{
				if ((this._DatPhongID != value))
				{
					if (this._tbl_DatPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDatPhongIDChanging(value);
					this.SendPropertyChanging();
					this._DatPhongID = value;
					this.SendPropertyChanged("DatPhongID");
					this.OnDatPhongIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThuc", DbType="NVarChar(50)")]
		public string PhuongThuc
		{
			get
			{
				return this._PhuongThuc;
			}
			set
			{
				if ((this._PhuongThuc != value))
				{
					this.OnPhuongThucChanging(value);
					this.SendPropertyChanging();
					this._PhuongThuc = value;
					this.SendPropertyChanged("PhuongThuc");
					this.OnPhuongThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this.OnCreate_atChanging(value);
					this.SendPropertyChanging();
					this._Create_at = value;
					this.SendPropertyChanged("Create_at");
					this.OnCreate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Update_at
		{
			get
			{
				return this._Update_at;
			}
			set
			{
				if ((this._Update_at != value))
				{
					this.OnUpdate_atChanging(value);
					this.SendPropertyChanging();
					this._Update_at = value;
					this.SendPropertyChanged("Update_at");
					this.OnUpdate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this.OnDelete_atChanging(value);
					this.SendPropertyChanging();
					this._Delete_at = value;
					this.SendPropertyChanged("Delete_at");
					this.OnDelete_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_DatPhong_tbl_GiaoDich", Storage="_tbl_DatPhong", ThisKey="DatPhongID", OtherKey="DatPhongID", IsForeignKey=true)]
		public tbl_DatPhong tbl_DatPhong
		{
			get
			{
				return this._tbl_DatPhong.Entity;
			}
			set
			{
				tbl_DatPhong previousValue = this._tbl_DatPhong.Entity;
				if (((previousValue != value) 
							|| (this._tbl_DatPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_DatPhong.Entity = null;
						previousValue.tbl_GiaoDiches.Remove(this);
					}
					this._tbl_DatPhong.Entity = value;
					if ((value != null))
					{
						value.tbl_GiaoDiches.Add(this);
						this._DatPhongID = value.DatPhongID;
					}
					else
					{
						this._DatPhongID = default(int);
					}
					this.SendPropertyChanged("tbl_DatPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LoaiPhong")]
	public partial class tbl_LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LoaiPhongID;
		
		private string _TenLoaiPhong;
		
		private string _MoTa;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private System.Nullable<bool> _isDelete;
		
		private System.Nullable<System.DateTime> _Update_at;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private EntitySet<tbl_Phong> _tbl_Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiPhongIDChanging(int value);
    partial void OnLoaiPhongIDChanged();
    partial void OnTenLoaiPhongChanging(string value);
    partial void OnTenLoaiPhongChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnCreate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_atChanged();
    partial void OnisDeleteChanging(System.Nullable<bool> value);
    partial void OnisDeleteChanged();
    partial void OnUpdate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdate_atChanged();
    partial void OnDelete_atChanging(System.Nullable<System.DateTime> value);
    partial void OnDelete_atChanged();
    #endregion
		
		public tbl_LoaiPhong()
		{
			this._tbl_Phongs = new EntitySet<tbl_Phong>(new Action<tbl_Phong>(this.attach_tbl_Phongs), new Action<tbl_Phong>(this.detach_tbl_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhongID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LoaiPhongID
		{
			get
			{
				return this._LoaiPhongID;
			}
			set
			{
				if ((this._LoaiPhongID != value))
				{
					this.OnLoaiPhongIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhongID = value;
					this.SendPropertyChanged("LoaiPhongID");
					this.OnLoaiPhongIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiPhong", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiPhong
		{
			get
			{
				return this._TenLoaiPhong;
			}
			set
			{
				if ((this._TenLoaiPhong != value))
				{
					this.OnTenLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiPhong = value;
					this.SendPropertyChanged("TenLoaiPhong");
					this.OnTenLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(4000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this.OnCreate_atChanging(value);
					this.SendPropertyChanging();
					this._Create_at = value;
					this.SendPropertyChanged("Create_at");
					this.OnCreate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="Bit")]
		public System.Nullable<bool> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this.OnisDeleteChanging(value);
					this.SendPropertyChanging();
					this._isDelete = value;
					this.SendPropertyChanged("isDelete");
					this.OnisDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Update_at
		{
			get
			{
				return this._Update_at;
			}
			set
			{
				if ((this._Update_at != value))
				{
					this.OnUpdate_atChanging(value);
					this.SendPropertyChanging();
					this._Update_at = value;
					this.SendPropertyChanged("Update_at");
					this.OnUpdate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this.OnDelete_atChanging(value);
					this.SendPropertyChanging();
					this._Delete_at = value;
					this.SendPropertyChanged("Delete_at");
					this.OnDelete_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LoaiPhong_tbl_Phong", Storage="_tbl_Phongs", ThisKey="LoaiPhongID", OtherKey="LoaiPhongID")]
		public EntitySet<tbl_Phong> tbl_Phongs
		{
			get
			{
				return this._tbl_Phongs;
			}
			set
			{
				this._tbl_Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Phongs(tbl_Phong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LoaiPhong = this;
		}
		
		private void detach_tbl_Phongs(tbl_Phong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Phong")]
	public partial class tbl_Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PhongID;
		
		private string _SoPhong;
		
		private int _LoaiPhongID;
		
		private decimal _GiaMoiDem;
		
		private System.Nullable<int> _SucChuaToiDa;
		
		private string _MoTa;
		
		private string _TrangThai;
		
		private string _HinhAnh;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private System.Nullable<bool> _isDelete;
		
		private System.Nullable<System.DateTime> _Update_at;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private EntitySet<tbl_DatPhong> _tbl_DatPhongs;
		
		private EntitySet<tbl_PhongImage> _tbl_PhongImages;
		
		private EntityRef<tbl_LoaiPhong> _tbl_LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPhongIDChanging(int value);
    partial void OnPhongIDChanged();
    partial void OnSoPhongChanging(string value);
    partial void OnSoPhongChanged();
    partial void OnLoaiPhongIDChanging(int value);
    partial void OnLoaiPhongIDChanged();
    partial void OnGiaMoiDemChanging(decimal value);
    partial void OnGiaMoiDemChanged();
    partial void OnSucChuaToiDaChanging(System.Nullable<int> value);
    partial void OnSucChuaToiDaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnCreate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_atChanged();
    partial void OnisDeleteChanging(System.Nullable<bool> value);
    partial void OnisDeleteChanged();
    partial void OnUpdate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdate_atChanged();
    partial void OnDelete_atChanging(System.Nullable<System.DateTime> value);
    partial void OnDelete_atChanged();
    #endregion
		
		public tbl_Phong()
		{
			this._tbl_DatPhongs = new EntitySet<tbl_DatPhong>(new Action<tbl_DatPhong>(this.attach_tbl_DatPhongs), new Action<tbl_DatPhong>(this.detach_tbl_DatPhongs));
			this._tbl_PhongImages = new EntitySet<tbl_PhongImage>(new Action<tbl_PhongImage>(this.attach_tbl_PhongImages), new Action<tbl_PhongImage>(this.detach_tbl_PhongImages));
			this._tbl_LoaiPhong = default(EntityRef<tbl_LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PhongID
		{
			get
			{
				return this._PhongID;
			}
			set
			{
				if ((this._PhongID != value))
				{
					this.OnPhongIDChanging(value);
					this.SendPropertyChanging();
					this._PhongID = value;
					this.SendPropertyChanged("PhongID");
					this.OnPhongIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SoPhong
		{
			get
			{
				return this._SoPhong;
			}
			set
			{
				if ((this._SoPhong != value))
				{
					this.OnSoPhongChanging(value);
					this.SendPropertyChanging();
					this._SoPhong = value;
					this.SendPropertyChanged("SoPhong");
					this.OnSoPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhongID", DbType="Int NOT NULL")]
		public int LoaiPhongID
		{
			get
			{
				return this._LoaiPhongID;
			}
			set
			{
				if ((this._LoaiPhongID != value))
				{
					if (this._tbl_LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiPhongIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhongID = value;
					this.SendPropertyChanged("LoaiPhongID");
					this.OnLoaiPhongIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaMoiDem", DbType="Decimal(18,2) NOT NULL")]
		public decimal GiaMoiDem
		{
			get
			{
				return this._GiaMoiDem;
			}
			set
			{
				if ((this._GiaMoiDem != value))
				{
					this.OnGiaMoiDemChanging(value);
					this.SendPropertyChanging();
					this._GiaMoiDem = value;
					this.SendPropertyChanged("GiaMoiDem");
					this.OnGiaMoiDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChuaToiDa", DbType="Int")]
		public System.Nullable<int> SucChuaToiDa
		{
			get
			{
				return this._SucChuaToiDa;
			}
			set
			{
				if ((this._SucChuaToiDa != value))
				{
					this.OnSucChuaToiDaChanging(value);
					this.SendPropertyChanging();
					this._SucChuaToiDa = value;
					this.SendPropertyChanged("SucChuaToiDa");
					this.OnSucChuaToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(4000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this.OnCreate_atChanging(value);
					this.SendPropertyChanging();
					this._Create_at = value;
					this.SendPropertyChanged("Create_at");
					this.OnCreate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="Bit")]
		public System.Nullable<bool> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this.OnisDeleteChanging(value);
					this.SendPropertyChanging();
					this._isDelete = value;
					this.SendPropertyChanged("isDelete");
					this.OnisDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Update_at
		{
			get
			{
				return this._Update_at;
			}
			set
			{
				if ((this._Update_at != value))
				{
					this.OnUpdate_atChanging(value);
					this.SendPropertyChanging();
					this._Update_at = value;
					this.SendPropertyChanged("Update_at");
					this.OnUpdate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this.OnDelete_atChanging(value);
					this.SendPropertyChanging();
					this._Delete_at = value;
					this.SendPropertyChanged("Delete_at");
					this.OnDelete_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_DatPhong", Storage="_tbl_DatPhongs", ThisKey="PhongID", OtherKey="PhongID")]
		public EntitySet<tbl_DatPhong> tbl_DatPhongs
		{
			get
			{
				return this._tbl_DatPhongs;
			}
			set
			{
				this._tbl_DatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_PhongImage", Storage="_tbl_PhongImages", ThisKey="PhongID", OtherKey="PhongID")]
		public EntitySet<tbl_PhongImage> tbl_PhongImages
		{
			get
			{
				return this._tbl_PhongImages;
			}
			set
			{
				this._tbl_PhongImages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LoaiPhong_tbl_Phong", Storage="_tbl_LoaiPhong", ThisKey="LoaiPhongID", OtherKey="LoaiPhongID", IsForeignKey=true)]
		public tbl_LoaiPhong tbl_LoaiPhong
		{
			get
			{
				return this._tbl_LoaiPhong.Entity;
			}
			set
			{
				tbl_LoaiPhong previousValue = this._tbl_LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._tbl_LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_LoaiPhong.Entity = null;
						previousValue.tbl_Phongs.Remove(this);
					}
					this._tbl_LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.tbl_Phongs.Add(this);
						this._LoaiPhongID = value.LoaiPhongID;
					}
					else
					{
						this._LoaiPhongID = default(int);
					}
					this.SendPropertyChanged("tbl_LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_DatPhongs(tbl_DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = this;
		}
		
		private void detach_tbl_DatPhongs(tbl_DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = null;
		}
		
		private void attach_tbl_PhongImages(tbl_PhongImage entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = this;
		}
		
		private void detach_tbl_PhongImages(tbl_PhongImage entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PhongImages")]
	public partial class tbl_PhongImage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PhongImages;
		
		private int _PhongID;
		
		private string _Url;
		
		private EntityRef<tbl_Phong> _tbl_Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPhongImagesChanging(int value);
    partial void OnPhongImagesChanged();
    partial void OnPhongIDChanging(int value);
    partial void OnPhongIDChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    #endregion
		
		public tbl_PhongImage()
		{
			this._tbl_Phong = default(EntityRef<tbl_Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongImages", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PhongImages
		{
			get
			{
				return this._PhongImages;
			}
			set
			{
				if ((this._PhongImages != value))
				{
					this.OnPhongImagesChanging(value);
					this.SendPropertyChanging();
					this._PhongImages = value;
					this.SendPropertyChanged("PhongImages");
					this.OnPhongImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongID", DbType="Int NOT NULL")]
		public int PhongID
		{
			get
			{
				return this._PhongID;
			}
			set
			{
				if ((this._PhongID != value))
				{
					if (this._tbl_Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongIDChanging(value);
					this.SendPropertyChanging();
					this._PhongID = value;
					this.SendPropertyChanged("PhongID");
					this.OnPhongIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_PhongImage", Storage="_tbl_Phong", ThisKey="PhongID", OtherKey="PhongID", IsForeignKey=true)]
		public tbl_Phong tbl_Phong
		{
			get
			{
				return this._tbl_Phong.Entity;
			}
			set
			{
				tbl_Phong previousValue = this._tbl_Phong.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Phong.Entity = null;
						previousValue.tbl_PhongImages.Remove(this);
					}
					this._tbl_Phong.Entity = value;
					if ((value != null))
					{
						value.tbl_PhongImages.Add(this);
						this._PhongID = value.PhongID;
					}
					else
					{
						this._PhongID = default(int);
					}
					this.SendPropertyChanged("tbl_Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TaiKhoan")]
	public partial class tbl_TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TaiKhoanID;
		
		private string _MaTK;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _MatKhau;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private string _VaiTro;
		
		private System.Nullable<System.DateTime> _Update_at;
		
		private System.Nullable<bool> _isDelete;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private EntitySet<tbl_DatPhong> _tbl_DatPhongs;
		
		private EntityRef<tbl_VaiTro> _tbl_VaiTro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanIDChanging(int value);
    partial void OnTaiKhoanIDChanged();
    partial void OnMaTKChanging(string value);
    partial void OnMaTKChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnCreate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_atChanged();
    partial void OnVaiTroChanging(string value);
    partial void OnVaiTroChanged();
    partial void OnUpdate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdate_atChanged();
    partial void OnisDeleteChanging(System.Nullable<bool> value);
    partial void OnisDeleteChanged();
    partial void OnDelete_atChanging(System.Nullable<System.DateTime> value);
    partial void OnDelete_atChanged();
    #endregion
		
		public tbl_TaiKhoan()
		{
			this._tbl_DatPhongs = new EntitySet<tbl_DatPhong>(new Action<tbl_DatPhong>(this.attach_tbl_DatPhongs), new Action<tbl_DatPhong>(this.detach_tbl_DatPhongs));
			this._tbl_VaiTro = default(EntityRef<tbl_VaiTro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TaiKhoanID
		{
			get
			{
				return this._TaiKhoanID;
			}
			set
			{
				if ((this._TaiKhoanID != value))
				{
					this.OnTaiKhoanIDChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanID = value;
					this.SendPropertyChanged("TaiKhoanID");
					this.OnTaiKhoanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", AutoSync=AutoSync.Always, DbType="VarChar(5)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(255)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this.OnCreate_atChanging(value);
					this.SendPropertyChanging();
					this._Create_at = value;
					this.SendPropertyChanged("Create_at");
					this.OnCreate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					if (this._tbl_VaiTro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Update_at
		{
			get
			{
				return this._Update_at;
			}
			set
			{
				if ((this._Update_at != value))
				{
					this.OnUpdate_atChanging(value);
					this.SendPropertyChanging();
					this._Update_at = value;
					this.SendPropertyChanged("Update_at");
					this.OnUpdate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="Bit")]
		public System.Nullable<bool> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this.OnisDeleteChanging(value);
					this.SendPropertyChanging();
					this._isDelete = value;
					this.SendPropertyChanged("isDelete");
					this.OnisDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this.OnDelete_atChanging(value);
					this.SendPropertyChanging();
					this._Delete_at = value;
					this.SendPropertyChanged("Delete_at");
					this.OnDelete_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_TaiKhoan_tbl_DatPhong", Storage="_tbl_DatPhongs", ThisKey="TaiKhoanID", OtherKey="TaiKhoanID")]
		public EntitySet<tbl_DatPhong> tbl_DatPhongs
		{
			get
			{
				return this._tbl_DatPhongs;
			}
			set
			{
				this._tbl_DatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_VaiTro_tbl_TaiKhoan", Storage="_tbl_VaiTro", ThisKey="VaiTro", OtherKey="VaiTro", IsForeignKey=true)]
		public tbl_VaiTro tbl_VaiTro
		{
			get
			{
				return this._tbl_VaiTro.Entity;
			}
			set
			{
				tbl_VaiTro previousValue = this._tbl_VaiTro.Entity;
				if (((previousValue != value) 
							|| (this._tbl_VaiTro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_VaiTro.Entity = null;
						previousValue.tbl_TaiKhoans.Remove(this);
					}
					this._tbl_VaiTro.Entity = value;
					if ((value != null))
					{
						value.tbl_TaiKhoans.Add(this);
						this._VaiTro = value.VaiTro;
					}
					else
					{
						this._VaiTro = default(string);
					}
					this.SendPropertyChanged("tbl_VaiTro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_DatPhongs(tbl_DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_TaiKhoan = this;
		}
		
		private void detach_tbl_DatPhongs(tbl_DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_DanhSachDatPhong")]
	public partial class vw_DanhSachDatPhong
	{
		
		private int _DatPhongID;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.DateTime _NgayNhanPhong;
		
		private System.DateTime _NgayTraPhong;
		
		private System.Nullable<int> _SoLuongNguoi;
		
		private System.Nullable<decimal> _TongTien;
		
		private string _TrangThai;
		
		private string _GhiChu;
		
		private string _SoPhong;
		
		private int _PhongID;
		
		private int _TaiKhoanID;
		
		private string _MaTK;
		
		private string _HoTen;
		
		private System.Nullable<bool> _isDelete;
		
		public vw_DanhSachDatPhong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatPhongID", DbType="Int NOT NULL")]
		public int DatPhongID
		{
			get
			{
				return this._DatPhongID;
			}
			set
			{
				if ((this._DatPhongID != value))
				{
					this._DatPhongID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime2")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this._NgayDat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhanPhong", DbType="DateTime2 NOT NULL")]
		public System.DateTime NgayNhanPhong
		{
			get
			{
				return this._NgayNhanPhong;
			}
			set
			{
				if ((this._NgayNhanPhong != value))
				{
					this._NgayNhanPhong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTraPhong", DbType="DateTime2 NOT NULL")]
		public System.DateTime NgayTraPhong
		{
			get
			{
				return this._NgayTraPhong;
			}
			set
			{
				if ((this._NgayTraPhong != value))
				{
					this._NgayTraPhong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNguoi", DbType="Int")]
		public System.Nullable<int> SoLuongNguoi
		{
			get
			{
				return this._SoLuongNguoi;
			}
			set
			{
				if ((this._SoLuongNguoi != value))
				{
					this._SoLuongNguoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this._TongTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SoPhong
		{
			get
			{
				return this._SoPhong;
			}
			set
			{
				if ((this._SoPhong != value))
				{
					this._SoPhong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongID", DbType="Int NOT NULL")]
		public int PhongID
		{
			get
			{
				return this._PhongID;
			}
			set
			{
				if ((this._PhongID != value))
				{
					this._PhongID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanID", DbType="Int NOT NULL")]
		public int TaiKhoanID
		{
			get
			{
				return this._TaiKhoanID;
			}
			set
			{
				if ((this._TaiKhoanID != value))
				{
					this._TaiKhoanID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="VarChar(5)")]
		public string MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this._MaTK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="Bit")]
		public System.Nullable<bool> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this._isDelete = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_ThongKeDoanhThu")]
	public partial class vw_ThongKeDoanhThu
	{
		
		private System.Nullable<int> _Nam;
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<decimal> _TongDoanhThu;
		
		public vw_ThongKeDoanhThu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDoanhThu", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> TongDoanhThu
		{
			get
			{
				return this._TongDoanhThu;
			}
			set
			{
				if ((this._TongDoanhThu != value))
				{
					this._TongDoanhThu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_DanhSachPhong")]
	public partial class vw_DanhSachPhong
	{
		
		private int _PhongID;
		
		private string _SoPhong;
		
		private decimal _GiaMoiDem;
		
		private string _MoTa;
		
		private string _HinhAnh;
		
		private System.Nullable<int> _SucChuaToiDa;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private System.Nullable<bool> _isDelete;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private System.Nullable<System.DateTime> _Update_at;
		
		private string _TenLoaiPhong;
		
		public vw_DanhSachPhong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongID", DbType="Int NOT NULL")]
		public int PhongID
		{
			get
			{
				return this._PhongID;
			}
			set
			{
				if ((this._PhongID != value))
				{
					this._PhongID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SoPhong
		{
			get
			{
				return this._SoPhong;
			}
			set
			{
				if ((this._SoPhong != value))
				{
					this._SoPhong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaMoiDem", DbType="Decimal(18,2) NOT NULL")]
		public decimal GiaMoiDem
		{
			get
			{
				return this._GiaMoiDem;
			}
			set
			{
				if ((this._GiaMoiDem != value))
				{
					this._GiaMoiDem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(4000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChuaToiDa", DbType="Int")]
		public System.Nullable<int> SucChuaToiDa
		{
			get
			{
				return this._SucChuaToiDa;
			}
			set
			{
				if ((this._SucChuaToiDa != value))
				{
					this._SucChuaToiDa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this._Create_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="Bit")]
		public System.Nullable<bool> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this._isDelete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this._Delete_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Update_at
		{
			get
			{
				return this._Update_at;
			}
			set
			{
				if ((this._Update_at != value))
				{
					this._Update_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiPhong", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiPhong
		{
			get
			{
				return this._TenLoaiPhong;
			}
			set
			{
				if ((this._TenLoaiPhong != value))
				{
					this._TenLoaiPhong = value;
				}
			}
		}
	}
	
	public partial class sp_TimPhongResult
	{
		
		private int _PhongID;
		
		private string _SoPhong;
		
		private string _TenLoaiPhong;
		
		private decimal _GiaMoiDem;
		
		private System.Nullable<int> _SucChuaToiDa;
		
		private string _TrangThai;
		
		private string _MoTa;
		
		private string _HinhAnh;
		
		public sp_TimPhongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongID", DbType="Int NOT NULL")]
		public int PhongID
		{
			get
			{
				return this._PhongID;
			}
			set
			{
				if ((this._PhongID != value))
				{
					this._PhongID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SoPhong
		{
			get
			{
				return this._SoPhong;
			}
			set
			{
				if ((this._SoPhong != value))
				{
					this._SoPhong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiPhong", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiPhong
		{
			get
			{
				return this._TenLoaiPhong;
			}
			set
			{
				if ((this._TenLoaiPhong != value))
				{
					this._TenLoaiPhong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaMoiDem", DbType="Decimal(18,2) NOT NULL")]
		public decimal GiaMoiDem
		{
			get
			{
				return this._GiaMoiDem;
			}
			set
			{
				if ((this._GiaMoiDem != value))
				{
					this._GiaMoiDem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChuaToiDa", DbType="Int")]
		public System.Nullable<int> SucChuaToiDa
		{
			get
			{
				return this._SucChuaToiDa;
			}
			set
			{
				if ((this._SucChuaToiDa != value))
				{
					this._SucChuaToiDa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(4000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
	}
	
	public partial class sp_BaoCaoDoanhThuTheoThangResult
	{
		
		private int _Thang;
		
		private decimal _TongDoanhThu;
		
		public sp_BaoCaoDoanhThuTheoThangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int NOT NULL")]
		public int Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDoanhThu", DbType="Decimal(38,2) NOT NULL")]
		public decimal TongDoanhThu
		{
			get
			{
				return this._TongDoanhThu;
			}
			set
			{
				if ((this._TongDoanhThu != value))
				{
					this._TongDoanhThu = value;
				}
			}
		}
	}
	
	public partial class sp_BaoCaoDoanhThuDatPhongResult
	{
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<int> _Nam;
		
		private System.Nullable<int> _SoLuotDat;
		
		private System.Nullable<decimal> _DoanhThu;
		
		public sp_BaoCaoDoanhThuDatPhongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuotDat", DbType="Int")]
		public System.Nullable<int> SoLuotDat
		{
			get
			{
				return this._SoLuotDat;
			}
			set
			{
				if ((this._SoLuotDat != value))
				{
					this._SoLuotDat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoanhThu", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> DoanhThu
		{
			get
			{
				return this._DoanhThu;
			}
			set
			{
				if ((this._DoanhThu != value))
				{
					this._DoanhThu = value;
				}
			}
		}
	}
	
	public partial class sp_BaoCaoDoanhThuTheoThangResult1
	{
		
		private int _Thang;
		
		private decimal _TongDoanhThu;
		
		public sp_BaoCaoDoanhThuTheoThangResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int NOT NULL")]
		public int Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDoanhThu", DbType="Decimal(38,2) NOT NULL")]
		public decimal TongDoanhThu
		{
			get
			{
				return this._TongDoanhThu;
			}
			set
			{
				if ((this._TongDoanhThu != value))
				{
					this._TongDoanhThu = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
